### ISSUE TITLE
When logged in and first making a project, the status is Approved by default

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#11]
![image](https://user-images.githubusercontent.com/2099441/89482751-8966ae80-d768-11ea-914d-4357278b773f.png)

**Comment by awesomeisfree** [comment]
This is expected behavior if you are logged in as an admin. Whenever you do something as an Admin, it shortcuts all the approvals. I tried it as a student and it was draft status. Can you verify?
