### ISSUE TITLE
Untutorial Check box instead of "I'm finished/Done" button

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#13]
Students have ability to check/uncheck until they hit the final "I'm finished with this project" button. When they check, the step has some sort of disabled-like style.

**Comment by awesomeisfree** [comment]
I implemented a different metaphor where teachers can uncheck/check after students submit steps. And it shows colored icons depending on the status. Let me know if this still fits the vision

**Comment by madduccino** [comment]
I think so, closing this for now.
