### ISSUE TITLE
Recent Work "Work on Step x" inaccuracies

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#19]
All cases below tested with Frank.Gehry / architect.

If teacher disapproves step, it still tells students to work on the step after the one they submitted for review, whereas when you click inside, it says Keep it Up, you're on the disapproved step. I feel like the latter makes more sense.

![image](https://user-images.githubusercontent.com/2099441/91370470-716cd280-e7dc-11ea-863f-a833fbfdf81f.png)

**Comment by madduccino** [comment]
When I finish all the steps but teacher again disapproves of Step 1:

![image](https://user-images.githubusercontent.com/2099441/91371198-54390380-e7de-11ea-8734-5b26af9525d8.png)

**Comment by madduccino** [comment]
When I check out project for the first time and don't complete any steps:

![image](https://user-images.githubusercontent.com/2099441/91371797-06bd9600-e7e0-11ea-9e3a-90b70eb07161.png)

**Comment by awesomeisfree** [comment]
I unified the step determination. Everything draws from the same number now and the logic for that number is:
(The step number of the first step in Draft status) + 1.
Note that student progress only draws from steps that existed when the user checked out the project. If a progress object for whatever reason doesn't have a next step (e.g. they checked out but didn't touch anything) page will read work on project
