### ISSUE TITLE
Can't Publish to Universe

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#20]
Trying to publish Ghost Busters by Frank Gehry / architect but getting error

**Comment by awesomeisfree** [comment]
Was not able to reproduce. I published as Frank. Possibly fixed by an intermediary bug fix.

**Comment by madduccino** [comment]
As Serena.Williams / tennis:

![image](https://user-images.githubusercontent.com/2099441/92333043-43935380-f050-11ea-8d51-f115d2062a1d.png)

![image](https://user-images.githubusercontent.com/2099441/92333070-6a518a00-f050-11ea-9caa-63bccec90d69.png)

![image](https://user-images.githubusercontent.com/2099441/92333078-89501c00-f050-11ea-9727-a4e8979025e9.png)

**Comment by madduccino** [comment]
(It doesn't publish.)
