### ISSUE TITLE
Header fields for untutorial steps

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#27]
from....

Step 1
Use the cat sprite or delete it and add a new one of your preference. Also, add a new backdrop to decorate the scene.

to....

Step 1: Add a sprite and backdrop
Use the cat sprite or delete it and add a new one of your preference. Also, add a new backdrop to decorate the scene.

**Comment by awesomeisfree** [comment]
Fields added. Note: difficult to see with current css (it's behind the edit description button)
