### ISSUE TITLE
Specify the order of projects in launchpad

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#33]
Typically the untutorials in each level go from easy to hard so we should give the creator the option to specify the listing order when submitting a new untutorial.

**Comment by awesomeisfree** [comment]
How would a student know the listing order of the other projects? For example:
Animal piano has a list order of 15
Monster maker has a list order of 7
If a student wants to put their untutorial between them, how would they need to know to pick a number between 7 and 15?  

Also, why would a student put their untutorial at the end or in the middle. They'll want people to try it won't they? I feel like everyone will want it at the front.

If anything I feel like we should shuffle them every page load, so we can feature different student untutorials each time. I feel like this is a feature that doesn't jive well with student produced content. The launchpad is no longer bespoke hand designed content exclusively.

**Comment by awesomeisfree** [comment]
Even if you say, well the list order is exactly the order they appear in the list (e.g. animal piano would be the 15th item in the list), the student would have to gauge the difficulty of all the projects and tab back and count and figure out where they'd want it.

Also, depending on filters and searching, the order may change.

**Comment by madduccino** [comment]
So, I was thinking about this from the "Official untutorial" perspective. A good example is Easy Cash. It's a tough Level 2 and it was originally one of the first projects listed in Level 2 which meant that many students were going to it first when they were not ready so I moved it to the back of the line. 

Can we allow admin to have this option?

**Comment by madduccino** [comment]
I like the idea of shuffling for students.
