### ISSUE TITLE
Iframe example saga

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#40]
Instead of having the iframe in the untutorial description, could we have an iframe popup when you click into the untutorial. Similar to how this video pops up when you go to create a Scratch project:

![image](https://user-images.githubusercontent.com/2099441/94088028-4eced900-fddd-11ea-9f75-ddf262635ea2.png)

Then, you could have the option of pulling this back up by clicking a button/text/question mark.

Another thing I noticed when testing is students thinking they can click on the gif examples so that's something to watch.

**Comment by awesomeisfree** [comment]
This is wyswyg content (or at least html embedded content that needs to be pasted somewhere), so if you want something as elaborate as that, we either need to:
1) Make a button for it in the untut/wyswyg, teach students about iframes embeds and about how to use the button
2) Make it teacher only, which we've already discussed adding a 'edit html' button or we can add other types of buttons

We should discuss!

**Comment by madduccino** [comment]
I vote for the first option. I just committed a version where when you click on the untutorial from the launchpad, the title, description, and iframe pop up (when it is in the description.) They can play the game, then choose whether to code it or not. It's a direct response to a student asking, "How do I know if I want to make it?" when she clicked through to an untutorial that didn't have an iframe in the description. Once the user chooses to code it or click out, the iframe disappears but you can toggle it back out. That way the iframe isn't the focal point when you're ready to code.

I haven't factored in Woof/Web iframes yet into the design.
