### ISSUE TITLE
Launchpad filtering

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#5]
It's behaving slightly weirdly. For instance, in the screenshot below, Scratch shows up as what I'm selecting but nothing appears.

![image](https://user-images.githubusercontent.com/2099441/89414627-bc715980-d6f8-11ea-86aa-a2e59805ec61.png)

**Comment by awesomeisfree** [comment]
ah, it just needs an empty item to default to. It starts on Scratch, thus you can not select scratch

**Comment by awesomeisfree** [comment]
done... added to universe as well. Verify!

**Comment by madduccino** [comment]
It still feels slightly weird because I think it should go back to filter when you select something. For instance,

![image](https://user-images.githubusercontent.com/2099441/92335333-2799ad00-f064-11ea-887d-b889c6b6270d.png)

I selected Scratch so the filter defaulted to Woof. If I want to select Woof, I then have to select out of Woof and select Woof again. If it defaulted to Filter, I would skip first step/not be confused

**Comment by madduccino** [comment]
Closed in favor of #39
