### ISSUE TITLE
Show Example feature

### ISSUE THREAD

**Issue by madduccino** [awesomeisfree/coding.space#6]
In New Projects, add a “Show Example” button that allows you to paste in an iframe that is embedded in a given step. (Or paste in a link that is turned into an iframe behind the scenes)

**Comment by awesomeisfree** [comment]
I'm gonna say this is doable, but we'd need to discuss some limitations. We have no idea what they'll link to or how big it'll need to be. Like a scratch iframe needs to be 400x by 600px, but a woofjs iframe would need to be 700px by 500px, etc. Plus they could link to... anything.

**Comment by madduccino** [comment]
True, let's put this on the list of things.
